import java_cup.runtime.*;
import java.io.*;

action code {: :};
parser code {: :};
init with {: :};

/* define how to connect to the scanner! */
scan with {: return s.next_token(); :};


/* symbol list */

terminal ID, LPAR, RPAR, CONCAT, COMMA, LBRACK, RBRACK, IF, ELSE, PREFIX, SUFFIX, STRING_LITERAL

terminal String ID, STRING_LITERAL

non terminal entry, declaration,  params, params_list, call, args, args_list, expr, concat_expr, atom, condition


/* Grammar Implemenatation */
entry ::= declaration call

declaration ::=  ID LPAR params RPAR LBRACK expr RBRACK declaration | 
params ::= params_list | 
params_list ::= ID COMMA params_list | ID

call ::= ID LPAR args RPAR call | 
args ::= args_list | 
args_list ::= expr COMMA args_list | expr

expr ::= IF condition expr ELSE expr | atom concat_expr
concat_expr ::= CONCAT atom concat_expr | 
atom ::= ID:id  {: RESULT = new String s; :} 
        | STRING_LITERAL | call

condition ::= atom PREFIX atom | atom SUFFIX atom

















/*

entry -> declaration call

declaration -> ID (params) {expr} declaration | e
params ->  params_list | e 
params_list -> ID , params_list | ID 


call -> ID (args) call  | e 
args ->  args_list | e
args_list -> expr , args_list | expr 

expr -> IF condition expr ELSE expr  | atom concat_expr
concat_expr -> + atom concat_expr | e 
atom -> ID | STR | call 

condition -> atom prefix atom | atom suffix atom 

*/
